# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nikita Telkar
description:      'PhD student by day, PhD student by night.'
url:              https://drive.google.com/file/d/1_g2uZWVYm_fC_mOfhlWjVlvYtkvXg5kl/view?usp=sharing
baseurl:          /hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars

github:
  repo:           https://github.com/nikita-telkar
